### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by GrayFace** [sandstranger/ArxLibertatis-android-port#7]
Steps I've done:
1. Installed v1.3.5 from F-Droid
2. Copied *.pak, cfg_default.ini, graph\* and misc\* from GOG version to MyData\Arx\ folder on the phone
3. Ran PC version of arx-libertatis to produce cfg.ini and copied it too
4. Set the game on Android to use folder (it asked for permission to access that specific folder and I granted it)
5. It crashes each time I try to run it (by pressing the arrow button):
![x7CaX6opAHY](https://github.com/user-attachments/assets/e398c58f-4168-4e09-8b15-ac52299fa870)
![StPFzVGO2Wk](https://github.com/user-attachments/assets/38a8eed7-ec46-47e5-b65b-f342d9858d53)
![OGhedt5d7U4](https://github.com/user-attachments/assets/feff9f46-e78f-4c31-9c78-9969fb8eb445)

**Comment by GrayFace** [comment]
OS: Android 13 / MIUI Global 14.0.8

**Comment by sandstranger** [comment]
По логу ругается, что не выдан пермишен на доступ к файлам.
Вообще уже были такие баги и ранее

**Comment by GrayFace** [comment]
> По логу ругается, что не выдан пермишен на доступ к файлам.

Да, тоже заметил. Вариант решения:

DevilutionX, например, просто говорит положить файлы в Android/Data/пакет и никаких проблем, а у Arx невозможно выбрать эту папку, т.к. диалог выбора папки не позволяет.

**Comment by sandstranger** [comment]
![Screenshot_20241223-235442](https://github.com/user-attachments/assets/786edbba-c324-4eb4-88c4-b560c2709897)
В новой версии можно будет выбрать папку приложения для кеша
